import XCTest

@testable import podcasts

/// Parity tests for `CloudFingerprinter` and `CloudReferenceMatcher` against
/// the server's Go `SpectralGenerator`. The expected hashes come from
/// `CloudFingerprintParityData`, generated by the Go test
/// `internal/fingerprint/client_fixtures_test.go` — do not hand-edit.
final class CloudFingerprinterTests: XCTestCase {

    // Mirrors the Go deterministicSignal (client_fixtures_test.go): runtime
    // variables + identical expression order so every double is bit-equal.
    private func deterministicSignal(sampleRate: Int, seconds: Double) -> [Float] {
        let freqs: [Double] = [440.0, 1000.0, 2500.0, 880.0]
        let amps: [Double] = [0.5, 0.3, 0.2, 0.1]
        let phases: [Double] = [0.0, 0.5, 1.2, 0.0]
        let n = Int(Double(sampleRate) * seconds)
        return (0..<n).map { i in
            let t = Double(i) / Double(sampleRate)
            var v = 0.0
            for k in freqs.indices {
                v += amps[k] * Foundation.sin(2.0 * Double.pi * freqs[k] * t + phases[k])
            }
            return Float(v)
        }
    }

    private func stereo(sampleRate: Int, seconds: Double) -> [Float] {
        let mono = deterministicSignal(sampleRate: sampleRate, seconds: seconds)
        return mono.flatMap { [$0, $0] }
    }

    private func windows(samples: [Float], channels: Int, sampleRate: Int) -> [CloudFingerprinter.Window] {
        let fp = CloudFingerprinter()
        // Push in 8192-sample chunks to exercise the streaming path.
        var offset = 0
        while offset < samples.count {
            let end = min(offset + 8192, samples.count)
            fp.pushSamples(Array(samples[offset..<end]), channels: channels, sampleRate: sampleRate)
            offset = end
        }
        return fp.finish()
    }

    func test16kMonoWindowsMatchServerReferenceHashes() {
        let output = windows(
            samples: deterministicSignal(sampleRate: 16000, seconds: 10.0),
            channels: 1,
            sampleRate: 16000
        )
        XCTAssertEqual(output.count, 3)
        for (i, expected) in CloudFingerprintParityData.signal16kMonoWindows.enumerated() {
            XCTAssertEqual(output[i].timestampSec, i, "window \(i) start_sec")
            XCTAssertEqual(output[i].hashes, expected, "window \(i) hashes must match server SpectralGenerator")
        }
    }

    func test44kHzStereoWindowsMatchServerReferenceHashes() {
        let output = windows(
            samples: stereo(sampleRate: 44100, seconds: 10.0),
            channels: 2,
            sampleRate: 44100
        )
        XCTAssertEqual(output.count, 3)
        for (i, expected) in CloudFingerprintParityData.signal44kStereoWindows.enumerated() {
            XCTAssertEqual(output[i].hashes, expected, "resampled window \(i) hashes must match server")
        }
    }

    func testChunkedPushesEqualSinglePush() {
        let samples = deterministicSignal(sampleRate: 16000, seconds: 10.0)

        let chunked = windows(samples: samples, channels: 1, sampleRate: 16000)

        let single = CloudFingerprinter()
        single.pushSamples(samples, channels: 1, sampleRate: 16000)
        let whole = single.finish()

        XCTAssertEqual(chunked, whole)
    }

    func testWindowsAreEmittedOnlyOnceLookaheadIsAvailable() {
        let fp = CloudFingerprinter()
        // Push only the first 8 s of the 10 s signal: window 0 cannot complete
        // until frames past its target zone exist (~9.5 s of audio).
        let samples = deterministicSignal(sampleRate: 16000, seconds: 10.0)
        fp.pushSamples(Array(samples[0..<(16000 * 8)]), channels: 1, sampleRate: 16000)
        XCTAssertTrue(fp.windowsSoFar.isEmpty, "no window should be emitted after only 8 s")
    }
}

final class CloudReferenceMatcherTests: XCTestCase {

    func testExactWindowMatchScoresOneAtCorrectCheckpoint() {
        let matcher = CloudReferenceMatcher()
        let query = CloudFingerprintParityData.signal16kMonoWindows[0]
        matcher.add(timestampSeconds: 0, hashes: query, durationSeconds: 8)
        matcher.add(timestampSeconds: 1, hashes: [1111, 2222, 3333], durationSeconds: 8)
        matcher.add(timestampSeconds: 2, hashes: [4444, 5555, 6666], durationSeconds: 8)

        let matches = matcher.findTopMatches(queryHashes: query, maxResults: 2)

        XCTAssertEqual(matches.count, 2)
        XCTAssertEqual(matches[0].timestampSeconds, 0)
        XCTAssertEqual(matches[0].score, 1.0)
    }

    func testDifferentAudioScoresBelowMatchFloor() {
        let matcher = CloudReferenceMatcher()
        matcher.add(timestampSeconds: 0, hashes: CloudFingerprintParityData.signal16kMonoWindows[0], durationSeconds: 8)

        let matches = matcher.findTopMatches(queryHashes: [42, 99, 12345], maxResults: 1)

        XCTAssertNotNil(matches.first)
        XCTAssertLessThan(matches[0].score, 0.5)
    }

    func testPartialOverlapScoresProportionally() {
        let score = CloudReferenceMatcher.overlapScore([1, 2, 3, 4, 5], [1, 2, 3, 99, 100])
        XCTAssertEqual(score, Float(3) / 5, accuracy: 0.0001)
    }

    func testEmptyQueryNeverMatches() {
        let matcher = CloudReferenceMatcher()
        matcher.add(timestampSeconds: 0, hashes: CloudFingerprintParityData.signal16kMonoWindows[0], durationSeconds: 8)
        XCTAssertTrue(matcher.findTopMatches(queryHashes: [], maxResults: 1).isEmpty)
    }
}
